# data setting
data_name: covid
n_channels: 1
n_classes: 2
classes: normal covid-19

# root of real dataset
root1: './data2/splits'

##root of fake dataset
root2: './data2/fake'

# class name:  for gan
class_name: 'covid-19'

# model input size
cnn_image_size: 224
dcgan_image_size: 224

mean: 0
std: 1