# data setting
data_name: pneumonia
n_channels: 1
n_classes: 2
classes: normal pneumonia

# root of real dataset
root1: './data1/real'

#root of fake dataset
root2: './data1/fake'

# class name: normal or pneumonia for gan
class_name: 'normal'

# model input size
cnn_image_size: 224
dcgan_image_size: 64

mean: 0
std: 1